---
apiVersion: v1
kind: List
items:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongo
    labels:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: database
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: employee-manager
        app.kubernetes.io/component: database
    template:
      metadata:
        labels:
          app.kubernetes.io/name: employee-manager
          app.kubernetes.io/component: database
        name: mongo
      spec:
        containers:
        - name: mongo
          image: centos/mongodb-34-centos7
          ports:
          - name: mongo
            containerPort: 27017
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
-
  apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    labels:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: database
  spec:
    ports:
      - port: 27017
        targetPort: 27017
    selector:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: database
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nodejs-app
    labels:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: nodejs-app
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: employee-manager
        app.kubernetes.io/component: nodejs-app
    template:
      metadata:
        labels:
          app.kubernetes.io/name: employee-manager
          app.kubernetes.io/component: nodejs-app
        name: nodejs-app
      spec:
        containers:
        - name: web-app
          image: "sleshchenko/nodejs-mongo-sample:latest"
          ports:
          - containerPort: 3000
            name: http-server
          env:
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_PORT
              value: "27017"
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
-
  apiVersion: v1
  kind: Service
  metadata:
    name: web
    labels:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: nodejs-app
  spec:
    ports:
      - name: web
        port: 80
        targetPort: 3000
        protocol: TCP
    selector:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: nodejs-app
-
  apiVersion: v1
  kind: Route
  metadata:
    name: nodejs-ingress
    labels:
      app.kubernetes.io/name: employee-manager
      app.kubernetes.io/component: nodejs-app
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: web
    port:
      targetPort: web